@startuml
!define LIGHTBLUE
!include ./style.puml

skinparam nodesep 50
skinparam ranksep 100

frame "WAN" {
  frame "LAN" {
    node "Kiosk Workstation" <<device>> as workstation {
      component "Sharing-Station App" <<application>> as  application
      component "MQTT Broker" <<service>> as mqttBroker
    }
    node "MQTT Embedded Client" <<device>> as mqttClient
    node "Webcam" <<device>> as webcam
    node "Coin Slot" <<device>> as coinSlot
    node "Card Terminal" <<device>> as cardTerminal

    webcam -- application: <<protocol>>\nserial
    cardTerminal -- mqttClient: <<protocol>>\nserial
    coinSlot -- mqttClient: <<protocol>>\nserial
  
  mqttBroker -- mqttClient: <<protocol>>\nmqtt
  mqttBroker -- application: <<protocol>>\nmqtt over\nwebsockets
  }
  interface "Wordpress Newsletter API" as newsletterApi 

  node "Server" <<device>> as cmsServer {
    component "CMS" <<application>> as cms
    component "Web Server" <<application>> as webServer
    database "Database" as database
    cms -- database
  }
}

webServer -up- application: <<protocol>>\nhttp(s)
cms -up- application: <<protocol>>\nhttp(s)
newsletterApi -up- application: <<protocol>>\nhttp(s)
@enduml